export interface CCAbility {
  id: string
  class: string
  ability: string
  drCategory: string
  duration: string
  dispellable: boolean
  breaksOnDamage: boolean
  specialization: string
  talent: string
}

export const ccAbilities: CCAbility[] = [
  // Mage
  {
    id: "1",
    class: "Mage",
    ability: "Polymorph",
    drCategory: "Disorient",
    duration: "60s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "2",
    class: "Mage",
    ability: "Ring of Frost",
    drCategory: "Disorient",
    duration: "10s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "3",
    class: "Mage",
    ability: "Dragon's Breath",
    drCategory: "Disorient",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Fire",
    talent: "Base",
  },
  {
    id: "4",
    class: "Mage",
    ability: "Frost Nova",
    drCategory: "Root",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "5",
    class: "Mage",
    ability: "Freeze (Pet)",
    drCategory: "Root",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Frost",
    talent: "Base",
  },
  {
    id: "6",
    class: "Mage",
    ability: "Counterspell",
    drCategory: "Silence",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  // Druid
  {
    id: "7",
    class: "Druid",
    ability: "Hibernate",
    drCategory: "Disorient",
    duration: "40s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "8",
    class: "Druid",
    ability: "Cyclone",
    drCategory: "Incapacitate",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "9",
    class: "Druid",
    ability: "Entangling Roots",
    drCategory: "Root",
    duration: "30s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "10",
    class: "Druid",
    ability: "Mass Entanglement",
    drCategory: "Root",
    duration: "30s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "11",
    class: "Druid",
    ability: "Mighty Bash",
    drCategory: "Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "12",
    class: "Druid",
    ability: "Maim",
    drCategory: "Stun",
    duration: "1-5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Feral",
    talent: "Base",
  },
  {
    id: "13",
    class: "Druid",
    ability: "Incapacitating Roar",
    drCategory: "Incapacitate",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Guardian",
    talent: "Talent",
  },
  // Warrior
  {
    id: "14",
    class: "Warrior",
    ability: "Storm Bolt",
    drCategory: "Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "15",
    class: "Warrior",
    ability: "Shockwave",
    drCategory: "Stun",
    duration: "2s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "16",
    class: "Warrior",
    ability: "Intimidating Shout",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "17",
    class: "Warrior",
    ability: "Piercing Howl",
    drCategory: "Slow",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "18",
    class: "Warrior",
    ability: "Warbringer",
    drCategory: "Root",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Talent",
  },
  // Rogue
  {
    id: "19",
    class: "Rogue",
    ability: "Sap",
    drCategory: "Incapacitate",
    duration: "60s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "20",
    class: "Rogue",
    ability: "Blind",
    drCategory: "Disorient",
    duration: "60s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "21",
    class: "Rogue",
    ability: "Kidney Shot",
    drCategory: "Stun",
    duration: "1-6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "22",
    class: "Rogue",
    ability: "Cheap Shot",
    drCategory: "Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "All",
    talent: "Base",
  },
  {
    id: "23",
    class: "Rogue",
    ability: "Gouge",
    drCategory: "Incapacitate",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "All",
    talent: "Talent",
  },
  {
    id: "24",
    class: "Rogue",
    ability: "Between the Eyes",
    drCategory: "Stun",
    duration: "1-8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Outlaw",
    talent: "Base",
  },
]

export const drCategories = [
  {
    name: "Stun",
    description: "Prevents all actions. Target cannot move, cast, or use abilities.",
    color: "bg-red-500/10 text-red-500 border-red-500/20",
  },
  {
    name: "Incapacitate",
    description: "Prevents all actions but breaks on damage. Target is completely disabled until hit.",
    color: "bg-purple-500/10 text-purple-500 border-purple-500/20",
  },
  {
    name: "Disorient",
    description: "Prevents all actions and breaks on damage. Similar to incapacitate but different DR category.",
    color: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
  },
  {
    name: "Fear",
    description: "Target runs around in fear, unable to control movement. Breaks on damage.",
    color: "bg-orange-500/10 text-orange-500 border-orange-500/20",
  },
  {
    name: "Root",
    description: "Prevents movement but allows casting and ability use.",
    color: "bg-green-500/10 text-green-500 border-green-500/20",
  },
  {
    name: "Silence",
    description: "Prevents spellcasting but allows movement and physical abilities.",
    color: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  },
  {
    name: "Slow",
    description: "Reduces movement speed significantly.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
]

export const classColors: Record<string, string> = {
  Mage: "text-cyan-400",
  Druid: "text-orange-400",
  Warrior: "text-amber-600",
  Rogue: "text-yellow-400",
  Paladin: "text-pink-400",
  Priest: "text-gray-300",
  Warlock: "text-purple-400",
  Hunter: "text-green-400",
  Shaman: "text-blue-400",
  "Death Knight": "text-red-400",
  Monk: "text-teal-400",
  "Demon Hunter": "text-violet-400",
}
