export interface CCAbility {
  id: string;
  class: string;
  ability: string;
  drCategory: string;
  duration: string;
  dispellable: boolean;
  breaksOnDamage: boolean;
  specialization: string;
  talent: string;
}

export const ccAbilities: CCAbility[] = [
  {
    id: "1",
    class: "Death Knight",
    ability: "Chains of Ice",
    drCategory: "Controlled Root",
    duration: "20s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Death Knight",
    talent: "Base",
  },
  {
    id: "2",
    class: "Death Knight",
    ability: "Remorseless Winter (at 5 stacks)",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Frost",
    talent: "Talent",
  },
  {
    id: "3",
    class: "Death Knight",
    ability: "Asphyxiate",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight",
    talent: "Talent",
  },
  {
    id: "4",
    class: "Death Knight",
    ability: "Monstrous Blow (Dark Transformation)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Unholy",
    talent: "Base",
  },
  {
    id: "5",
    class: "Death Knight",
    ability: "Gnaw",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Unholy",
    talent: "Base",
  },
  {
    id: "6",
    class: "Death Knight",
    ability: "Strangulate",
    drCategory: "Silence",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Death Knight",
    talent: "Base",
  },
  {
    id: "7",
    class: "Druid",
    ability: "Disorienting Roar",
    drCategory: "Confuse",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Talent",
  },
  {
    id: "8",
    class: "Druid",
    ability: "Entangling Roots",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "9",
    class: "Druid",
    ability: "Entangling Roots (Force of Nature Treants)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid: Balance/Feral",
    talent: "Talent",
  },
  {
    id: "10",
    class: "Druid",
    ability: "Nature's Grasp",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "11",
    class: "Druid",
    ability: "Mass Entanglement",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Talent",
  },
  {
    id: "12",
    class: "Druid",
    ability: "Symbiosis Frost Nova (Feral)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid: Feral",
    talent: "Base",
  },
  {
    id: "13",
    class: "Druid",
    ability: "Symbiosis HoJ (Boomy)",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Druid: Balance",
    talent: "Base",
  },
  {
    id: "14",
    class: "Druid",
    ability: "Maim",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "15",
    class: "Druid",
    ability: "Mighty Bash",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Talent",
  },
  {
    id: "16",
    class: "Druid",
    ability: "Pounce",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "17",
    class: "Mage",
    ability: "Deep Freeze",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
  },
  {
    id: "18",
    class: "Druid",
    ability: "Hibernate",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "19",
    class: "Druid",
    ability: "Symbiosis Intimidating Shout (Resto)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Druid: Restoration",
    talent: "Base",
  },
  {
    id: "20",
    class: "Druid",
    ability: "Solar Beam",
    drCategory: "No DR",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid: Balance",
    talent: "Base",
  },
  {
    id: "21",
    class: "Druid",
    ability: "Wild Charge Immobilize",
    drCategory: "No DR",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Talent",
  },
  {
    id: "22",
    class: "Druid",
    ability: "Cyclone",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "23",
    class: "Druid",
    ability: "Faerie Fire (Glyph of Fae Silence)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
  },
  {
    id: "24",
    class: "Hunter",
    ability: "Scatter Shot",
    drCategory: "Confuse",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
  },
  {
    id: "25",
    class: "Hunter",
    ability: "Narrow Escape",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Talent",
  },
  {
    id: "26",
    class: "Hunter",
    ability: "Intimidate",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Talent",
  },
  {
    id: "27",
    class: "Hunter",
    ability: "Binding Shot",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Talent",
  },
  {
    id: "28",
    class: "Hunter",
    ability: "Freezing Trap",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
  },
  {
    id: "29",
    class: "Hunter",
    ability: "Wyvern Sting",
    drCategory: "Disorient",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Talent",
  },
  {
    id: "30",
    class: "Hunter",
    ability: "Scare Beast",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
  },
  {
    id: "31",
    class: "Hunter",
    ability: "Entrapment",
    drCategory: "Self DR (Root)",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Base",
  },
  {
    id: "32",
    class: "Hunter",
    ability: "Silencing Shot",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Base",
  },
  {
    id: "33",
    class: "Mage",
    ability: "Dragon's Breath",
    drCategory: "Confuse",
    duration: "1.5s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: Fire",
    talent: "Base",
  },
  {
    id: "34",
    class: "Mage",
    ability: "Frost Nova",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
  },
  {
    id: "35",
    class: "Mage",
    ability: "Freeze (Water Ele)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
  },
  {
    id: "36",
    class: "Warrior",
    ability: "Shockwave",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
  },
  {
    id: "37",
    class: "Warrior",
    ability: "Storm Bolt",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
  },
  {
    id: "38",
    class: "Mage",
    ability: "Polymorph",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Base",
  },
  {
    id: "39",
    class: "Mage",
    ability: "Ring of Frost",
    drCategory: "Disorient",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Talent",
  },
  {
    id: "40",
    class: "Mage",
    ability: "Ice Ward",
    drCategory: "Self DR (Root)",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Talent",
  },
  {
    id: "41",
    class: "Mage",
    ability: "Improved Counterspell",
    drCategory: "Silence",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
  },
  {
    id: "42",
    class: "Mage",
    ability: "Frostjaw",
    drCategory: "Silence",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Talent",
  },
  {
    id: "43",
    class: "Monk",
    ability: "Disable (If already Snared)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk",
    talent: "Base",
  },
  {
    id: "44",
    class: "Monk",
    ability: "Symbiosis (MW) Entangling Roots",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk: Mistweaver",
    talent: "Base",
  },
  {
    id: "45",
    class: "Monk",
    ability: "Leg Sweep",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
  },
  {
    id: "46",
    class: "Monk",
    ability: "Clash",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk: Brewmaster",
    talent: "Base",
  },
  {
    id: "47",
    class: "Monk",
    ability: "Fists of Fury",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk: Windwalker",
    talent: "Base",
  },
  {
    id: "48",
    class: "Monk",
    ability: "Charging Ox Wave",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
  },
  {
    id: "49",
    class: "Monk",
    ability: "Grapple Weapon",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Base",
  },
  {
    id: "50",
    class: "Monk",
    ability: "Paralysis",
    drCategory: "Disorient",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk",
    talent: "Base",
  },
  {
    id: "51",
    class: "Monk",
    ability: "Ring of Peace",
    drCategory: "No DR",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
  },
  {
    id: "52",
    class: "Monk",
    ability: "Spear Hand Strike",
    drCategory: "Silence",
    duration: "2s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Base",
  },
  {
    id: "53",
    class: "Paladin",
    ability: "Hammer(Fist) of Justice",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Talent",
  },
  {
    id: "54",
    class: "Paladin",
    ability: "Holy Wrath (Undead)",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Talent",
  },
  {
    id: "55",
    class: "Paladin",
    ability: "Blinding Light (Glyphed)",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Base",
  },
  {
    id: "56",
    class: "Paladin",
    ability: "Repentance",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Talent",
  },
  {
    id: "57",
    class: "Paladin",
    ability: "Blinding Light",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Base",
  },
  {
    id: "58",
    class: "Paladin",
    ability: "Turn Evil",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Talent",
  },
  {
    id: "59",
    class: "Paladin",
    ability: "Avenger's Shield",
    drCategory: "Silence",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin: Protection",
    talent: "Base",
  },
  {
    id: "60",
    class: "Priest",
    ability: "Holy Word Chastise",
    drCategory: "Confuse",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Holy",
    talent: "Base",
  },
  {
    id: "61",
    class: "Priest",
    ability: "Void Tendril's Grasp",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest",
    talent: "Talent",
  },
  {
    id: "62",
    class: "Priest",
    ability: "Mind Blast (Glyphed)",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest: Shadow",
    talent: "Base",
  },
  {
    id: "63",
    class: "Priest",
    ability: "Psychic Horror",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
  },
  {
    id: "64",
    class: "Priest",
    ability: "Shackle Undead",
    drCategory: "Disorient",
    duration: "50s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Base",
  },
  {
    id: "65",
    class: "Priest",
    ability: "Psychic Scream",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Base",
  },
  {
    id: "66",
    class: "Priest",
    ability: "Psychic Terror (Psyfiend)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Talent",
  },
  {
    id: "67",
    class: "Priest",
    ability: "Psychic Horror",
    drCategory: "Horror",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
  },
  {
    id: "68",
    class: "Priest",
    ability: "Vampiric Touch Dispelled",
    drCategory: "No DR",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
  },
  {
    id: "69",
    class: "Priest",
    ability: "Symbiosis Cyclone (Holy)",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest",
    talent: "Base",
  },
  {
    id: "70",
    class: "Priest",
    ability: "Dominate Mind",
    drCategory: "Self DR",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Talent",
  },
  {
    id: "71",
    class: "Priest",
    ability: "Silence",
    drCategory: "Silence",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
  },
  {
    id: "72",
    class: "Rogue",
    ability: "Paralytic Poison (Shiv)",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Talent",
  },
  {
    id: "73",
    class: "Rogue",
    ability: "Kidney Shot (full)",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "74",
    class: "Rogue",
    ability: "Cheap Shot",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "75",
    class: "Rogue",
    ability: "Dismantle",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "76",
    class: "Rogue",
    ability: "Sap",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "77",
    class: "Rogue",
    ability: "Gouge",
    drCategory: "Disorient",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "78",
    class: "Rogue",
    ability: "Blind",
    drCategory: "Fear",
    duration: "10s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "79",
    class: "Rogue",
    ability: "Paralysis (Paralytic Poison)",
    drCategory: "Random Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Talent",
  },
  {
    id: "80",
    class: "Rogue",
    ability: "Garrote",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
  },
  {
    id: "81",
    class: "Shaman",
    ability: "Earthgrab (Totem)",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Talent",
  },
  {
    id: "82",
    class: "Shaman",
    ability: "Freeze",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Talent",
  },
  {
    id: "83",
    class: "Shaman",
    ability: "Static Charge (Capacitor Totem)",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
  },
  {
    id: "84",
    class: "Shaman",
    ability: "Pulverize (Earth Ele)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
  },
  {
    id: "85",
    class: "Shaman",
    ability: "Hex",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Shaman: All",
    talent: "Base",
  },
  {
    id: "86",
    class: "Shaman",
    ability: "Earthquake",
    drCategory: "Random Stun",
    duration: "2s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
  },
  {
    id: "87",
    class: "Shaman",
    ability: "Bind Elemental",
    drCategory: "Self DR (Banish)",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Shaman: All",
    talent: "Base",
  },
  {
    id: "88",
    class: "Warlock",
    ability: "Shadowfury",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Talent",
  },
  {
    id: "89",
    class: "Warlock",
    ability: "Summon Infernal",
    drCategory: "Controlled Stun",
    duration: "2s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock: Destruction",
    talent: "Base",
  },
  {
    id: "90",
    class: "Warlock",
    ability: "Axe Toss (Felguard)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
  },
  {
    id: "91",
    class: "Warlock",
    ability: "Disarm (Voidwalker)",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Base",
  },
  {
    id: "92",
    class: "Warlock",
    ability: "Fear",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: All",
    talent: "Base",
  },
  {
    id: "93",
    class: "Warlock",
    ability: "Howl of Terror",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: All",
    talent: "Base",
  },
  {
    id: "94",
    class: "Warlock",
    ability: "Sleep",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: Demonology",
    talent: "Base",
  },
  {
    id: "95",
    class: "Warlock",
    ability: "Seduction (Succubus)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
  },
  {
    id: "96",
    class: "Warlock",
    ability: "Mesmerize (Shivarra)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
  },
  {
    id: "97",
    class: "Warlock",
    ability: "Mortal Coil",
    drCategory: "Horror",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Talent",
  },
  {
    id: "98",
    class: "Warlock",
    ability: "Blood Horror",
    drCategory: "Horror",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Talent",
  },
  {
    id: "99",
    class: "Warlock",
    ability: "Unstable Affliction (Silence when dispelled)",
    drCategory: "No DR",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: Affliction",
    talent: "Base",
  },
  {
    id: "100",
    class: "Warlock",
    ability: "Banish",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
  },
  {
    id: "101",
    class: "Warlock",
    ability: "Spell Lock (Fel Hound)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
  },
  {
    id: "102",
    class: "Warlock",
    ability: "Optical Blast (Observer)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
  },
  {
    id: "103",
    class: "Warrior",
    ability: "Staggering Shout",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Warrior",
    talent: "Talent",
  },
  {
    id: "104",
    class: "Warrior",
    ability: "Warbringer",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
  },
  {
    id: "105",
    class: "Druid",
    ability: "Bear Hug",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid: Guardian",
    talent: "Base",
  },
  {
    id: "106",
    class: "Mage",
    ability: "Combustion Impact",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: Fire",
    talent: "Base",
  },
  {
    id: "107",
    class: "Warrior",
    ability: "Disarm",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Base",
  },
  {
    id: "108",
    class: "Warrior",
    ability: "Intimidating Shout",
    drCategory: "Fear",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Warrior",
    talent: "Base",
  },
  {
    id: "109",
    class: "Warrior",
    ability: "Dragon Roar",
    drCategory: "Random Stun",
    duration: "0.5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
  },
  {
    id: "110",
    class: "Warrior",
    ability: "Charge",
    drCategory: "Self DR",
    duration: "1.5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Base",
  },
];

export const drCategories = [
  // {
  //   name: "Stun",
  //   description:
  //     "Prevents all actions. Target cannot move, cast, or use abilities.",
  //   color: "bg-red-500/10 text-red-500 border-red-500/20",
  // },
  {
    name: "Incapacitate",
    description:
      "Prevents all actions but breaks on damage. Target is completely disabled until hit.",
    color: "bg-purple-500/10 text-purple-500 border-purple-500/20",
  },
  {
    name: "Disorient",
    description:
      "Prevents all actions and breaks on damage. Similar to incapacitate but different DR category.",
    color: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
  },
  {
    name: "Fear",
    description:
      "Target runs around in fear, unable to control movement. Breaks on damage.",
    color: "bg-orange-500/10 text-orange-500 border-orange-500/20",
  },
  // {
  //   name: "Root",
  //   description: "Prevents movement but allows casting and ability use.",
  //   color: "bg-green-500/10 text-green-500 border-green-500/20",
  // },
  {
    name: "Silence",
    description:
      "Prevents spellcasting but allows movement and physical abilities.",
    color: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  },
  {
    name: "Slow",
    description: "Reduces movement speed significantly.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Controlled Stun",
    description: "Deliberately applied stun.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Controlled Root",
    description: "Deliberately applied stun.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Self DR",
    description: "Abilities that only DR with themselves.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
];

export const classColors: Record<string, string> = {
  Mage: "text-cyan-400",
  Druid: "text-orange-400",
  Warrior: "text-amber-600",
  Rogue: "text-yellow-400",
  Paladin: "text-pink-400",
  Priest: "text-gray-300",
  Warlock: "text-purple-400",
  Hunter: "text-green-400",
  Shaman: "text-blue-400",
  "Death Knight": "text-red-400",
  Monk: "text-teal-400",
  "Demon Hunter": "text-violet-400",
};
