export interface CCAbility {
  id: string;
  class: string;
  ability: string;
  drCategory: string;
  duration: string;
  dispellable: boolean;
  breaksOnDamage: boolean;
  specialization: string;
  talent: string;
  cooldown: string;
  wowhead_link: string;
}

export const ccAbilities: CCAbility[] = [
  {
    id: "1",
    class: "Death Knight",
    ability: "Chains of Ice",
    drCategory: "Controlled Root",
    duration: "20s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Frost/Unholy",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=61077/chains-of-ice" data-wowhead="spell=61077">Chains of Ice</a>',
  },
  {
    id: "2",
    class: "Death Knight",
    ability: "Remorseless Winter (at 5 stacks)",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Frost",
    talent: "Talent",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=48721/remorseless-winter" data-wowhead="spell=48721">Remorseless Winter (at 5 stacks)</a>',
  },
  {
    id: "3",
    class: "Death Knight",
    ability: "Asphyxiate",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=108194/asphyxiate" data-wowhead="spell=108194">Asphyxiate</a>',
  },
  {
    id: "4",
    class: "Death Knight",
    ability: "Monstrous Blow (Dark Transformation)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Unholy",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=91797/gnaw" data-wowhead="spell=91797">Monstrous Blow (Dark Transformation)</a>',
  },
  {
    id: "5",
    class: "Death Knight",
    ability: "Gnaw",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Death Knight: Unholy",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=91797/gnaw" data-wowhead="spell=91797">Gnaw</a>',
  },
  {
    id: "6",
    class: "Death Knight",
    ability: "Strangulate",
    drCategory: "Silence",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Death Knight",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=7867/strangulate" data-wowhead="spell=7867">Strangulate</a>',
  },
  {
    id: "7",
    class: "Druid",
    ability: "Disorienting Roar",
    drCategory: "Confuse",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=99/disorienting-roar" data-wowhead="spell=99">Disorienting Roar</a>',
  },
  {
    id: "8",
    class: "Druid",
    ability: "Entangling Roots",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=339/entangling-roots" data-wowhead="spell=339">Entangling Roots</a>',
  },
  {
    id: "9",
    class: "Druid",
    ability: "Entangling Roots (Force of Nature Treants)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid: Balance/Feral",
    talent: "Talent",
    cooldown: "20sec (x3)",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=339/entangling-roots" data-wowhead="spell=339">Entangling Roots</a>',
  },
  {
    id: "10",
    class: "Druid",
    ability: "Nature's Grasp",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=53312/natures-grasp" data-wowhead="spell=53312">Nature\'s Grasp</a>',
  },
  {
    id: "11",
    class: "Druid",
    ability: "Mass Entanglement",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=102359/mass-entanglement" data-wowhead="spell=102359">Mass Entanglement</a>',
  },
  {
    id: "12",
    class: "Druid",
    ability: "Symbiosis Frost Nova (Feral)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid: Feral",
    talent: "Base",
    cooldown: "5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=122/frost-nova" data-wowhead="spell=122">Symbiosis Frost Nova (Feral)</a>',
  },
  {
    id: "13",
    class: "Druid",
    ability: "Symbiosis HoJ (Boomy)",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Druid: Balance",
    talent: "Base",
    cooldown: "5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=853/hammer-of-justice" data-wowhead="spell=853">Symbiosis HoJ (Boomy)</a>',
  },
  {
    id: "14",
    class: "Druid",
    ability: "Maim",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
    cooldown: "10sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=22570/maim" data-wowhead="spell=22570">Maim</a>',
  },
  {
    id: "15",
    class: "Druid",
    ability: "Mighty Bash",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Talent",
    cooldown: "50sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=99160/mighty-bash" data-wowhead="spell=99160">Mighty Bash</a>',
  },
  {
    id: "16",
    class: "Druid",
    ability: "Pounce",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
    cooldown: "10sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=9005/pounce" data-wowhead="spell=9005">Pounce</a>',
  },
  {
    id: "17",
    class: "Mage",
    ability: "Deep Freeze",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=44572/deep-freeze" data-wowhead="spell=44572">Deep Freeze</a>',
  },
  {
    id: "18",
    class: "Druid",
    ability: "Hibernate",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Druid",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=2137/hibernate" data-wowhead="spell=2137">Hibernate</a>',
  },
  {
    id: "19",
    class: "Druid",
    ability: "Symbiosis Intimidating Shout (Resto)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Druid: Restoration",
    talent: "Base",
    cooldown: "5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=686/intimidating-shout" data-wowhead="spell=686">Symbiosis Intimidating Shout (Resto)</a>',
  },
  {
    id: "20",
    class: "Druid",
    ability: "Solar Beam",
    drCategory: "No DR",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid: Balance",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=78675/solar-beam" data-wowhead="spell=78675">Solar Beam</a>',
  },
  {
    id: "21",
    class: "Druid",
    ability: "Wild Charge Immobilize",
    drCategory: "No DR",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Talent",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=102352/wild-charge" data-wowhead="spell=102352">Wild Charge Immobilize</a>',
  },
  {
    id: "22",
    class: "Druid",
    ability: "Cyclone",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=33786/cyclone" data-wowhead="spell=33786">Cyclone</a>',
  },
  {
    id: "23",
    class: "Druid",
    ability: "Faerie Fire (Glyph of Fae Silence)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Druid",
    talent: "Base",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=770/faerie-fire" data-wowhead="spell=770">Faerie Fire (Glyph of Fae Silence)</a>',
  },
  {
    id: "24",
    class: "Hunter",
    ability: "Scatter Shot",
    drCategory: "Confuse",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=19503/scatter-shot" data-wowhead="spell=19503">Scatter Shot</a>',
  },
  {
    id: "25",
    class: "Hunter",
    ability: "Narrow Escape",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Talent",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=328328/narrow-escape" data-wowhead="spell=328328">Narrow Escape</a>',
  },
  {
    id: "26",
    class: "Hunter",
    ability: "Intimidate",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Talent",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=19577/intimidate" data-wowhead="spell=19577">Intimidate</a>',
  },
  {
    id: "27",
    class: "Hunter",
    ability: "Binding Shot",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=109248/binding-shot" data-wowhead="spell=109248">Binding Shot</a>',
  },
  {
    id: "28",
    class: "Hunter",
    ability: "Freezing Trap",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=3355/freezing-trap" data-wowhead="spell=3355">Freezing Trap</a>',
  },
  {
    id: "29",
    class: "Hunter",
    ability: "Wyvern Sting",
    drCategory: "Disorient",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=86395/wyvern-sting" data-wowhead="spell=86395">Wyvern Sting</a>',
  },
  {
    id: "30",
    class: "Hunter",
    ability: "Scare Beast",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Hunter: All",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=1513/scare-beast" data-wowhead="spell=1513">Scare Beast</a>',
  },
  {
    id: "31",
    class: "Hunter",
    ability: "Entrapment",
    drCategory: "Self DR (Root)",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Base",
    cooldown: "30sec (x2)",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=194345/entrapment" data-wowhead="spell=194345">Entrapment</a>',
  },
  {
    id: "32",
    class: "Hunter",
    ability: "Silencing Shot",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Hunter: All",
    talent: "Base",
    cooldown: "24sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=154876/silencing-shot" data-wowhead="spell=154876">Silencing Shot</a>',
  },
  {
    id: "33",
    class: "Mage",
    ability: "Dragon's Breath",
    drCategory: "Confuse",
    duration: "1.5s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: Fire",
    talent: "Base",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=31661/dragons-breath" data-wowhead="spell=31661">Dragon\'s Breath</a>',
  },
  {
    id: "34",
    class: "Mage",
    ability: "Frost Nova",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
    cooldown: "25sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=122/frost-nova" data-wowhead="spell=122">Frost Nova</a>',
  },
  {
    id: "35",
    class: "Mage",
    ability: "Freeze (Water Ele)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
    cooldown: "25sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=33395/freeze" data-wowhead="spell=33395">Freeze (Water Ele)</a>',
  },
  {
    id: "36",
    class: "Warrior",
    ability: "Shockwave",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
    cooldown: "40sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=46968/shockwave" data-wowhead="spell=46968">Shockwave</a>',
  },
  {
    id: "37",
    class: "Warrior",
    ability: "Storm Bolt",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=107570/storm-bolt" data-wowhead="spell=107570">Storm Bolt</a>',
  },
  {
    id: "38",
    class: "Mage",
    ability: "Polymorph",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=118/polymorph" data-wowhead="spell=118">Polymorph</a>',
  },
  {
    id: "39",
    class: "Mage",
    ability: "Ring of Frost",
    drCategory: "Disorient",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=82676/ring-of-frost" data-wowhead="spell=82676">Ring of Frost</a>',
  },
  {
    id: "40",
    class: "Mage",
    ability: "Ice Ward",
    drCategory: "Self DR (Root)",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Mage: All",
    talent: "Talent",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=111301/ice-ward" data-wowhead="spell=111301">Ice Ward</a>',
  },
  {
    id: "41",
    class: "Mage",
    ability: "Improved Counterspell",
    drCategory: "Silence",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Base",
    cooldown: "24sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=2139/counterspell" data-wowhead="spell=2139">Improved Counterspell</a>',
  },
  {
    id: "42",
    class: "Mage",
    ability: "Frostjaw",
    drCategory: "Silence",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: All",
    talent: "Talent",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=102051/frostjaw" data-wowhead="spell=102051">Frostjaw</a>',
  },
  {
    id: "43",
    class: "Monk",
    ability: "Disable (If already Snared)",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=116095/disable" data-wowhead="spell=116095">Disable (If already Snared)</a>',
  },
  {
    id: "44",
    class: "Monk",
    ability: "Symbiosis (MW) Entangling Roots",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk: Mistweaver",
    talent: "Base",
    cooldown: "5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=339/entangling-roots" data-wowhead="spell=339">Symbiosis (MW) Entangling Roots</a>',
  },
  {
    id: "45",
    class: "Monk",
    ability: "Leg Sweep",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=115802/leg-sweep" data-wowhead="spell=115802">Leg Sweep</a>',
  },
  {
    id: "46",
    class: "Monk",
    ability: "Clash",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk: Brewmaster",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=116781/clash" data-wowhead="spell=116781">Clash</a>',
  },
  {
    id: "47",
    class: "Monk",
    ability: "Fists of Fury",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk: Windwalker",
    talent: "Base",
    cooldown: "25sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=117964/fists-of-fury" data-wowhead="spell=117964">Fists of Fury</a>',
  },
  {
    id: "48",
    class: "Monk",
    ability: "Charging Ox Wave",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=132039/charging-ox-wave" data-wowhead="spell=132039">Charging Ox Wave</a>',
  },
  {
    id: "49",
    class: "Monk",
    ability: "Grapple Weapon",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=117368/grapple-weapon" data-wowhead="spell=117368">Grapple Weapon</a>',
  },
  {
    id: "50",
    class: "Monk",
    ability: "Paralysis",
    drCategory: "Disorient",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Monk",
    talent: "Base",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=115292/paralysis" data-wowhead="spell=115292">Paralysis</a>',
  },
  {
    id: "51",
    class: "Monk",
    ability: "Ring of Peace",
    drCategory: "No DR",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=116844/ring-of-peace" data-wowhead="spell=116844">Ring of Peace</a>',
  },
  {
    id: "52",
    class: "Monk",
    ability: "Spear Hand Strike",
    drCategory: "Silence",
    duration: "2s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Monk",
    talent: "Base",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=116709/spear-hand-strike" data-wowhead="spell=116709">Spear Hand Strike</a>',
  },
  {
    id: "53",
    class: "Paladin",
    ability: "Hammer(Fist) of Justice",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Talent",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=853/hammer-of-justice" data-wowhead="spell=853">Hammer(Fist) of Justice</a>',
  },
  {
    id: "54",
    class: "Paladin",
    ability: "Holy Wrath (Undead)",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Talent",
    cooldown: "9sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=104270/holy-wrath" data-wowhead="spell=104270">Holy Wrath (Undead)</a>',
  },
  {
    id: "55",
    class: "Paladin",
    ability: "Blinding Light (Glyphed)",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin",
    talent: "Base",
    cooldown: "2min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=105421/blinding-light" data-wowhead="spell=105421">Blinding Light (Glyphed)</a>',
  },
  {
    id: "56",
    class: "Paladin",
    ability: "Repentance",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Talent",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=20066/repentance" data-wowhead="spell=20066">Repentance</a>',
  },
  {
    id: "57",
    class: "Paladin",
    ability: "Blinding Light",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Base",
    cooldown: "2min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=105421/blinding-light" data-wowhead="spell=105421">Blinding Light</a>',
  },
  {
    id: "58",
    class: "Paladin",
    ability: "Turn Evil",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Paladin",
    talent: "Talent",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=10326/turn-evil" data-wowhead="spell=10326">Turn Evil</a>',
  },
  {
    id: "59",
    class: "Paladin",
    ability: "Avenger's Shield",
    drCategory: "Silence",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Paladin: Protection",
    talent: "Base",
    cooldown: "15sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=31935/avengers-shield" data-wowhead="spell=31935">Avenger\'s Shield</a>',
  },
  {
    id: "60",
    class: "Priest",
    ability: "Holy Word Chastise",
    drCategory: "Confuse",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Holy",
    talent: "Base",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=88625/holy-word-chastise" data-wowhead="spell=88625">Holy Word Chastise</a>',
  },
  {
    id: "61",
    class: "Priest",
    ability: "Void Tendril's Grasp",
    drCategory: "Controlled Root",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=108920/void-tendrils" data-wowhead="spell=108920">Void Tendril\'s Grasp</a>',
  },
  {
    id: "62",
    class: "Priest",
    ability: "Mind Blast (Glyphed)",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest: Shadow",
    talent: "Base",
    cooldown: "8sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=8092/mind-blast" data-wowhead="spell=8092">Mind Blast (Glyphed)</a>',
  },
  {
    id: "63",
    class: "Priest",
    ability: "Psychic Horror",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=64044/psychic-horror" data-wowhead="spell=64044">Psychic Horror</a>',
  },
  {
    id: "64",
    class: "Priest",
    ability: "Shackle Undead",
    drCategory: "Disorient",
    duration: "50s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=9484/shackle-undead" data-wowhead="spell=9484">Shackle Undead</a>',
  },
  {
    id: "65",
    class: "Priest",
    ability: "Psychic Scream",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Base",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=10890/psychic-scream" data-wowhead="spell=10890">Psychic Scream</a>',
  },
  {
    id: "66",
    class: "Priest",
    ability: "Psychic Terror (Psyfiend)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=135046/psychic-terror" data-wowhead="spell=135046">Psychic Terror (Psyfiend)</a>',
  },
  {
    id: "67",
    class: "Priest",
    ability: "Psychic Horror",
    drCategory: "Horror",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=64044/psychic-horror" data-wowhead="spell=64044">Psychic Horror</a>',
  },
  {
    id: "68",
    class: "Priest",
    ability: "Vampiric Touch Dispelled",
    drCategory: "No DR",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=123011/silent-resolve" data-wowhead="spell=123011">Vampiric Touch Dispelled</a>',
  },
  {
    id: "69",
    class: "Priest",
    ability: "Symbiosis Cyclone (Holy)",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest",
    talent: "Base",
    cooldown: "5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=33786/cyclone" data-wowhead="spell=33786">Symbiosis Cyclone (Holy)</a>',
  },
  {
    id: "70",
    class: "Priest",
    ability: "Dominate Mind",
    drCategory: "Self DR",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Priest",
    talent: "Talent",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=605/dominate-mind" data-wowhead="spell=605">Dominate Mind</a>',
  },
  {
    id: "71",
    class: "Priest",
    ability: "Silence",
    drCategory: "Silence",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Priest: Shadow",
    talent: "Base",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=15487/silence" data-wowhead="spell=15487">Silence</a>',
  },
  {
    id: "72",
    class: "Rogue",
    ability: "Paralytic Poison (Shiv)",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Talent",
    cooldown: "10sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=112966/paralytic-poison" data-wowhead="spell=112966">Paralytic Poison (Shiv)</a>',
  },
  {
    id: "73",
    class: "Rogue",
    ability: "Kidney Shot (full)",
    drCategory: "Controlled Stun",
    duration: "6s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=408/kidney-shot" data-wowhead="spell=408">Kidney Shot (full)</a>',
  },
  {
    id: "74",
    class: "Rogue",
    ability: "Cheap Shot",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=1833/cheap-shot" data-wowhead="spell=1833">Cheap Shot</a>',
  },
  {
    id: "75",
    class: "Rogue",
    ability: "Dismantle",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=137687/dismantle" data-wowhead="spell=137687">Dismantle</a>',
  },
  {
    id: "76",
    class: "Rogue",
    ability: "Sap",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=6770/sap" data-wowhead="spell=6770">Sap</a>',
  },
  {
    id: "77",
    class: "Rogue",
    ability: "Gouge",
    drCategory: "Disorient",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "10sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=1776/gouge" data-wowhead="spell=1776">Gouge</a>',
  },
  {
    id: "78",
    class: "Rogue",
    ability: "Blind",
    drCategory: "Fear",
    duration: "10s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "2min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=2094/blind" data-wowhead="spell=2094">Blind</a>',
  },
  {
    id: "79",
    class: "Rogue",
    ability: "Paralysis (Paralytic Poison)",
    drCategory: "Random Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Talent",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=112966/paralytic-poison" data-wowhead="spell=112966">Paralysis (Paralytic Poison)</a>',
  },
  {
    id: "80",
    class: "Rogue",
    ability: "Garrote",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Rogue",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=1330/garrote" data-wowhead="spell=1330">Garrote</a>',
  },
  {
    id: "81",
    class: "Shaman",
    ability: "Earthgrab (Totem)",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=51485/earthgrab-totem" data-wowhead="spell=51485">Earthgrab (Totem)</a>',
  },
  {
    id: "82",
    class: "Shaman",
    ability: "Freeze",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Talent",
    cooldown: "6sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=8050/freeze" data-wowhead="spell=8050">Freeze</a>',
  },
  {
    id: "83",
    class: "Shaman",
    ability: "Static Charge (Capacitor Totem)",
    drCategory: "Controlled Stun",
    duration: "5s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=118905/capacitor-totem" data-wowhead="spell=118905">Static Charge (Capacitor Totem)</a>',
  },
  {
    id: "84",
    class: "Shaman",
    ability: "Pulverize (Earth Ele)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
    cooldown: "40sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=90788/pulverize" data-wowhead="spell=90788">Pulverize (Earth Ele)</a>',
  },
  {
    id: "85",
    class: "Shaman",
    ability: "Hex",
    drCategory: "Disorient",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Shaman: All",
    talent: "Base",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=51514/hex" data-wowhead="spell=51514">Hex</a>',
  },
  {
    id: "86",
    class: "Shaman",
    ability: "Earthquake",
    drCategory: "Random Stun",
    duration: "2s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Shaman: All",
    talent: "Base",
    cooldown: "10sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=61882/earthquake" data-wowhead="spell=61882">Earthquake</a>',
  },
  {
    id: "87",
    class: "Shaman",
    ability: "Bind Elemental",
    drCategory: "Self DR (Banish)",
    duration: "10s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Shaman: All",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=17926/bind-elemental" data-wowhead="spell=17926">Bind Elemental</a>',
  },
  {
    id: "88",
    class: "Warlock",
    ability: "Shadowfury",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=30283/shadowfury" data-wowhead="spell=30283">Shadowfury</a>',
  },
  {
    id: "89",
    class: "Warlock",
    ability: "Summon Infernal",
    drCategory: "Controlled Stun",
    duration: "2s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock: Destruction",
    talent: "Base",
    cooldown: "10min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=1122/summon-infernal" data-wowhead="spell=1122">Summon Infernal</a>',
  },
  {
    id: "90",
    class: "Warlock",
    ability: "Axe Toss (Felguard)",
    drCategory: "Controlled Stun",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=89766/axe-toss" data-wowhead="spell=89766">Axe Toss (Felguard)</a>',
  },
  {
    id: "91",
    class: "Warlock",
    ability: "Disarm (Voidwalker)",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=35102/disarm" data-wowhead="spell=35102">Disarm (Voidwalker)</a>',
  },
  {
    id: "92",
    class: "Warlock",
    ability: "Fear",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: All",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=5782/fear" data-wowhead="spell=5782">Fear</a>',
  },
  {
    id: "93",
    class: "Warlock",
    ability: "Howl of Terror",
    drCategory: "Fear",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: All",
    talent: "Base",
    cooldown: "40sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=6215/howl-of-terror" data-wowhead="spell=6215">Howl of Terror</a>',
  },
  {
    id: "94",
    class: "Warlock",
    ability: "Sleep",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock: Demonology",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/search?q=Sleep" data-wowhead="spell=0">Sleep</a>',
  },
  {
    id: "95",
    class: "Warlock",
    ability: "Seduction (Succubus)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
    cooldown: "6sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=6358/seduction" data-wowhead="spell=6358">Seduction (Succubus)</a>',
  },
  {
    id: "96",
    class: "Warlock",
    ability: "Mesmerize (Shivarra)",
    drCategory: "Fear",
    duration: "8s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=118699/mesmerize" data-wowhead="spell=118699">Mesmerize (Shivarra)</a>',
  },
  {
    id: "97",
    class: "Warlock",
    ability: "Mortal Coil",
    drCategory: "Horror",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Talent",
    cooldown: "45sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=6789/mortal-coil" data-wowhead="spell=6789">Mortal Coil</a>',
  },
  {
    id: "98",
    class: "Warlock",
    ability: "Blood Horror",
    drCategory: "Horror",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock",
    talent: "Talent",
    cooldown: "30sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=111397/blood-horror" data-wowhead="spell=111397">Blood Horror</a>',
  },
  {
    id: "99",
    class: "Warlock",
    ability: "Unstable Affliction (Silence when dispelled)",
    drCategory: "No DR",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: Affliction",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=30108/unstable-affliction" data-wowhead="spell=30108">Unstable Affliction (Silence when dispelled)</a>',
  },
  {
    id: "100",
    class: "Warlock",
    ability: "Banish",
    drCategory: "Self DR",
    duration: "6s",
    dispellable: true,
    breaksOnDamage: true,
    specialization: "Warlock",
    talent: "Base",
    cooldown: "N/A",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=710/banish" data-wowhead="spell=710">Banish</a>',
  },

  {
    id: "101",
    class: "Warlock",
    ability: "Spell Lock (Fel Hound)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
    cooldown: "24sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=19647/spell-lock" data-wowhead="spell=19647">Spell Lock (Fel Hound)</a>',
  },
  {
    id: "102",
    class: "Warlock",
    ability: "Optical Blast (Observer)",
    drCategory: "Silence",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warlock: All",
    talent: "Base",
    cooldown: "24sec",
    wowhead_link:
      '<a href="https://www.google.com/search?q=https://www.wowhead.com/mop-classic/spell%3D119827/optical-blast" data-wowhead="spell=119827">Optical Blast (Observer)</a>',
  },
  {
    id: "103",
    class: "Warrior",
    ability: "Staggering Shout",
    drCategory: "Controlled Root",
    duration: "5s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Warrior",
    talent: "Talent",
    cooldown: "40sec",
    wowhead_link:
      '<a href="https://www.google.com/search?q=https://www.wowhead.com/mop-classic/spell%3D107574/staggering-shout" data-wowhead="spell=107574">Staggering Shout</a>',
  },
  {
    id: "104",
    class: "Warrior",
    ability: "Warbringer",
    drCategory: "Controlled Root",
    duration: "4s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.google.com/search?q=https://www.wowhead.com/mop-classic/spell%3D100418/warbringer" data-wowhead="spell=100418">Warbringer</a>',
  },
  {
    id: "105",
    class: "Druid",
    ability: "Bear Hug",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Druid: Guardian",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.google.com/search?q=https://www.wowhead.com/mop-classic/spell%3D102558/bear-hug" data-wowhead="spell=102558">Bear Hug</a>',
  },
  {
    id: "106",
    class: "Mage",
    ability: "Combustion Impact",
    drCategory: "Controlled Stun",
    duration: "3s",
    dispellable: true,
    breaksOnDamage: false,
    specialization: "Mage: Fire",
    talent: "Base",
    cooldown: "2min",
    wowhead_link:
      '<a href="https://www.google.com/search?q=https://www.wowhead.com/mop-classic/spell%3D102148/impact" data-wowhead="spell=102148">Combustion Impact</a>',
  },
  {
    id: "107",
    class: "Warrior",
    ability: "Disarm",
    drCategory: "Disarm",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Base",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=676/disarm" data-wowhead="spell=676">Disarm</a>',
  },
  {
    id: "108",
    class: "Warrior",
    ability: "Intimidating Shout",
    drCategory: "Fear",
    duration: "8s",
    dispellable: false,
    breaksOnDamage: true,
    specialization: "Warrior",
    talent: "Base",
    cooldown: "1.5min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=5246/intimidating-shout" data-wowhead="spell=5246">Intimidating Shout</a>',
  },
  {
    id: "109",
    class: "Warrior",
    ability: "Dragon Roar",
    drCategory: "Random Stun",
    duration: "0.5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Talent",
    cooldown: "1min",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=118000/dragon-roar" data-wowhead="spell=118000">Dragon Roar</a>',
  },
  {
    id: "110",
    class: "Warrior",
    ability: "Charge",
    drCategory: "Self DR",
    duration: "1.5s",
    dispellable: false,
    breaksOnDamage: false,
    specialization: "Warrior",
    talent: "Base",
    cooldown: "20sec",
    wowhead_link:
      '<a href="https://www.wowhead.com/mop-classic/spell=100/charge" data-wowhead="spell=100">Charge</a>',
  },
];

export const drCategories = [
  // {
  //   name: "Stun",
  //   description:
  //     "Prevents all actions. Target cannot move, cast, or use abilities.",
  //   color: "bg-red-500/10 text-red-500 border-red-500/20",
  // },
  {
    name: "Incapacitate",
    description:
      "Prevents all actions but breaks on damage. Target is completely disabled until hit.",
    color: "bg-purple-500/10 text-purple-500 border-purple-500/20",
  },
  {
    name: "Disorient",
    description:
      "Prevents all actions and breaks on damage. Similar to incapacitate but different DR category.",
    color: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
  },
  {
    name: "Fear",
    description:
      "Target runs around in fear, unable to control movement. Breaks on damage.",
    color: "bg-orange-500/10 text-orange-500 border-orange-500/20",
  },
  // {
  //   name: "Root",
  //   description: "Prevents movement but allows casting and ability use.",
  //   color: "bg-green-500/10 text-green-500 border-green-500/20",
  // },
  {
    name: "Silence",
    description:
      "Prevents spellcasting but allows movement and physical abilities.",
    color: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  },
  {
    name: "Slow",
    description: "Reduces movement speed significantly.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Controlled Stun",
    description: "Deliberately applied stun.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Controlled Root",
    description: "Deliberately applied stun.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
  {
    name: "Self DR",
    description: "Abilities that only DR with themselves.",
    color: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
  },
];

export const classColors: Record<string, string> = {
  Mage: "text-cyan-400",
  Druid: "text-orange-400",
  Warrior: "text-yellow-900",
  Rogue: "text-yellow-400",
  Paladin: "text-pink-400",
  Priest: "text-gray-300",
  Warlock: "text-purple-400",
  Hunter: "text-green-400",
  Shaman: "text-blue-400",
  "Death Knight": "text-red-400",
  Monk: "text-teal-400",
  "Demon Hunter": "text-violet-400",
};
